language: node_js
node_js: 
    - "6"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git config --global user.email "zccz14@outlook.com"
    - git config --global user.name "zccz14"
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - npm i hexo-cli -g
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    cd public
    git init
    git add .
    git commit -m "Travis Deploy"
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://zccz14:$GITHUB_API_KEY@github.com/zccz14/zccz14.github.io master &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi