language: node_js
node_js: 
    - "6"
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git config --global user.email "zccz14@outlook.com"
    - git config --global user.name "zccz14"
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive